# .github/iterations.yml
# 🌀 Iteration Plan (manual reference or for use with custom scripts)

iterations:
  - name: Insert break
    status: break
    duration: null

  - name: Sprint 1 – Planning & Research
    status: current
    duration: 2 weeks

  - name: Insert break
    status: break
    duration: null

  - name: Sprint 2 – System Setup
    status: planned
    duration: 2 weeks

  - name: Insert break
    status: break
    duration: null

  - name: Sprint 3 – Core MVP Build
    status: planned
    duration: 2 weeks

  - name: Insert break
    status: break
    duration: null

  - name: Sprint 4 – Landing Page & Onboarding
    status: planned
    duration: 2 weeks

  - name: Insert break
    status: break
    duration: null

  - name: Sprint 5 – Marketing & Launch Prep
    status: planned
    duration: 2 weeks
