- name: blocked
  color: d73a4a
  description: This task is currently blocked and cannot move forward until something else is resolved.

- name: bug
  color: e11d21
  description: Something isn't working

- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation

- name: duplicate
  color: cfd3d7
  description: This issue or pull request already exists

- name: enhancement
  color: a2eeef
  description: New feature or request

- name: feature
  color: 0e8a16
  description: Core functions like chat UI, history storage, API proxy

- name: infra
  color: f9d0c4
  description: Deployment, container setup, backup

- name: learning
  color: fbca04
  description: What you’re researching or testing as you go

- name: marketing
  color: d876e3
  description: Landing page, SEO, outreach plan

- name: metrics
  color: 1d76db
  description: Log API calls, track latency, measure conversation stats

- name: planning
  color: bfdadc
  description: Tasks focused on defining, designing, or deciding what to build before development starts.

- name: stretch
  color: 5319e7
  description: Nice-to-have tasks or improvements that go beyond the core sprint goal.
