#!/bin/bash

# Scaffold Docs Directory Structure
# Based on the GitHub issue template: ISSUE_TEMPLATE/1-scaffold-docs.yml

set -e

echo "📁 Scaffolding docs directory structure..."

# Create directories
mkdir -p docs/blueprint
mkdir -p docs/planning  
mkdir -p docs/marketing
mkdir -p docs/design

# Create main docs README
cat > docs/README.md << 'EOF'
# 🗂 Product Documentation Index

This folder contains all structured documentation for this Slightly Better, Co. product. Each subfolder serves a specific purpose and corresponds to one or more AI personas and planning phases.

## 📁 Subdirectories

- [`blueprint/`](./blueprint/) – Foundational product vision and tech choices
- [`planning/`](./planning/) – Research, personas, and validation
- [`marketing/`](./marketing/) – Copywriting and outreach planning
- [`design/`](./design/) – Wireframes, UX notes, and UI specs

Each folder contains modular markdown files used by GitHub Copilot and CLI tools.
EOF

# Blueprint files
cat > docs/blueprint/README.md << 'EOF'
# 📘 Blueprint

This section contains the high-level product vision and technical architecture for this SaaS product.

## Files

- `product-brief.md` – What we're building and why
- `product-tech-stack.md` – Technologies and architecture choices

This documentation is typically created by the Founder and Project Manager.
EOF

cat > docs/blueprint/product-brief.md << 'EOF'
# Product Brief
EOF

cat > docs/blueprint/product-tech-stack.md << 'EOF'
# Product Tech Stack
EOF

# Planning files  
cat > docs/planning/README.md << 'EOF'
# 🔍 Planning

This section holds all early-stage research and validation data used to inform product direction and initial feature set.

## Files

- `pain-points.md` – Real user problems worth solving
- `user-personas.md` – Key user profiles and behaviors
- `competitive-analysis.md` – Market comparison and opportunity gaps
- `validation-survey.md` – Early feedback survey draft

Generated by: Research Analyst with PM oversight.
EOF

cat > docs/planning/pain-points.md << 'EOF'
# Pain Points
EOF

cat > docs/planning/user-personas.md << 'EOF'
# User Personas
EOF

cat > docs/planning/competitive-analysis.md << 'EOF'
# Competitive Analysis
EOF

cat > docs/planning/validation-survey.md << 'EOF'
# Validation Survey
EOF

# Marketing files
cat > docs/marketing/README.md << 'EOF'
# 📣 Marketing

This section includes key messaging assets and early outreach ideas to support landing page creation and go-to-market planning.

## Files

- `landing-page-copy.md` – Core marketing copy for your MVP site
- `audience-insights.md` – Demographics, motivators, and language

Generated by: Marketer persona, in collaboration with PM and UX.
EOF

cat > docs/marketing/landing-page-copy.md << 'EOF'
# Landing Page Copy
EOF

cat > docs/marketing/audience-insights.md << 'EOF'
# Audience Insights
EOF

# Design files
cat > docs/design/README.md << 'EOF'
# 🎨 Design

This section documents UI/UX artifacts, interaction flows, and layout sketches to guide visual implementation.

## Files

- `wireframes.md` – Low-fidelity layouts or Figma links
- `interaction-notes.md` – User flows, edge cases, and accessibility notes

Generated by: UI/UX Designer. Used by: Lead Developer.
EOF

cat > docs/design/wireframes.md << 'EOF'
# Wireframes
EOF

cat > docs/design/interaction-notes.md << 'EOF'
# Interaction Notes
EOF

echo "✅ Docs directory structure scaffolded successfully!"
echo "📝 Files created:"
echo "  - docs/README.md and all subdirectory READMEs"
echo "  - All planning, blueprint, marketing, and design stub files"
echo "🚀 Ready for content population by personas!"